apiVersion: v1
kind: PersistentVolumeClaim
metadata:
     name: mypvc1
spec:
  storageClassName: mystorageclass1
  accessModes:
      - ReadWriteOnce
  resources:
      requests:
          storage: 15Gi